dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
node_js:
  - "iojs"
  - "8"
before_install: 
  - gem install bundler -v 1.16.1
  - npm install -g puppeteer
  - npm install
matrix:
  allow_failures:
    - rvm: ruby-head

